CREATE TABLE teams (
    team CHAR(3) NOT NULL,
    location VARCHAR(20) NOT NULL,
    name VARCHAR(20),
    leag CHAR(1) NOT NULL CHECK (leag in ("A", "N")),
    PRIMARY KEY (team, leag)
);
CREATE TABLE players (
    ilkid CHAR(9) NOT NULL UNIQUE,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    position CHAR(1) NOT NULL CHECK (position in ("C", "F", "G")),
    firstseason SMALLINT NOT NULL,
    lastseason SMALLINT NOT NULL,
    h_feet TINYINT CHECK (h_feet >= 0),
    h_inches DECIMAL(3, 1),
    weight SMALLINT CHECK (weight >= 0),
    college VARCHAR(30),
    birthdate CHAR(19),
    PRIMARY KEY (ilkid)
);
CREATE TABLE player_playoffs (
    ilkid VARCHAR(9) NOT NULL,
    year SMALLINT NOT NULL,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    team CHAR(3) NOT NULL,
    leag CHAR(1) NOT NULL,
    gp MEDIUMINT DEFAULT 0,
    minutes MEDIUMINT DEFAULT 0,
    pts MEDIUMINT DEFAULT 0,
    dreb MEDIUMINT DEFAULT 0,
    oreb MEDIUMINT DEFAULT 0,
    reb MEDIUMINT DEFAULT 0,
    asts MEDIUMINT DEFAULT 0,
    stl MEDIUMINT DEFAULT 0,
    blk MEDIUMINT DEFAULT 0,
    turnover MEDIUMINT DEFAULT 0,
    pf MEDIUMINT DEFAULT 0,
    fga MEDIUMINT DEFAULT 0,
    fgm MEDIUMINT DEFAULT 0,
    fta MEDIUMINT DEFAULT 0,
    ftm MEDIUMINT DEFAULT 0,
    tpa MEDIUMINT DEFAULT 0,
    tpm MEDIUMINT DEFAULT 0,
    PRIMARY KEY (ilkid, year, team, leag),
    FOREIGN KEY (ilkid, firstname, lastname) REFERENCES player(ilkid, firstname, lastname),
    FOREIGN KEY (team, leag) REFERENCES teams(team, leag)
);
CREATE TABLE player_playoffs_career (
    ilkid VARCHAR(9) NOT NULL,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    leag CHAR(1) NOT NULL,
    gp MEDIUMINT DEFAULT 0,
    minutes MEDIUMINT DEFAULT 0,
    pts MEDIUMINT DEFAULT 0,
    dreb MEDIUMINT DEFAULT 0,
    oreb MEDIUMINT DEFAULT 0,
    reb MEDIUMINT DEFAULT 0,
    asts MEDIUMINT DEFAULT 0,
    stl MEDIUMINT DEFAULT 0,
    blk MEDIUMINT DEFAULT 0,
    turnover MEDIUMINT DEFAULT 0,
    pf MEDIUMINT DEFAULT 0,
    fga MEDIUMINT DEFAULT 0,
    fgm MEDIUMINT DEFAULT 0,
    fta MEDIUMINT DEFAULT 0,
    ftm MEDIUMINT DEFAULT 0,
    tpa MEDIUMINT DEFAULT 0,
    tpm MEDIUMINT DEFAULT 0,
    PRIMARY KEY(ilkid, leag),
    FOREIGN KEY (ilkid, firstname, lastname) REFERENCES player(ilkid, firstname, lastname),
    FOREIGN KEY (leag) REFERENCES teams(leag)
);
CREATE TABLE player_regular_season (
    ilkid VARCHAR(9) NOT NULL,
    year SMALLINT NOT NULL,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    team CHAR(3) NOT NULL,
    leag CHAR(1) NOT NULL,
    gp MEDIUMINT DEFAULT 0,
    minutes MEDIUMINT DEFAULT 0,
    pts MEDIUMINT DEFAULT 0,
    dreb MEDIUMINT DEFAULT 0,
    oreb MEDIUMINT DEFAULT 0,
    reb MEDIUMINT DEFAULT 0,
    asts MEDIUMINT DEFAULT 0,
    stl MEDIUMINT DEFAULT 0,
    blk MEDIUMINT DEFAULT 0,
    turnover MEDIUMINT DEFAULT 0,
    pf MEDIUMINT DEFAULT 0,
    fga MEDIUMINT DEFAULT 0,
    fgm MEDIUMINT DEFAULT 0,
    fta MEDIUMINT DEFAULT 0,
    ftm MEDIUMINT DEFAULT 0,
    tpa MEDIUMINT DEFAULT 0,
    tpm MEDIUMINT DEFAULT 0,
    PRIMARY KEY (ilkid, year, team, leag),
    FOREIGN KEY (ilkid, firstname, lastname) REFERENCES player(ilkid, firstname, lastname),
    FOREIGN KEY (team, leag) REFERENCES teams(team, leag)
);
CREATE TABLE player_regular_season_career (
    ilkid VARCHAR(9) NOT NULL,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    leag CHAR(1) NOT NULL,
    gp MEDIUMINT DEFAULT 0,
    minutes MEDIUMINT DEFAULT 0,
    pts MEDIUMINT DEFAULT 0,
    dreb MEDIUMINT DEFAULT 0,
    oreb MEDIUMINT DEFAULT 0,
    reb MEDIUMINT DEFAULT 0,
    asts MEDIUMINT DEFAULT 0,
    stl MEDIUMINT DEFAULT 0,
    blk MEDIUMINT DEFAULT 0,
    turnover MEDIUMINT DEFAULT 0,
    pf MEDIUMINT DEFAULT 0,
    fga MEDIUMINT DEFAULT 0,
    fgm MEDIUMINT DEFAULT 0,
    fta MEDIUMINT DEFAULT 0,
    ftm MEDIUMINT DEFAULT 0,
    tpa MEDIUMINT DEFAULT 0,
    tpm MEDIUMINT DEFAULT 0,
    PRIMARY KEY(ilkid, leag),
    FOREIGN KEY (ilkid, firstname, lastname) REFERENCES player(ilkid, firstname, lastname),
    FOREIGN KEY (leag) REFERENCES teams(leag)
);
CREATE TABLE coaches_career (
    coachid VARCHAR(9) NOT NULL UNIQUE,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    season_win MEDIUMINT DEFAULT 0,
    season_loss MEDIUMINT DEFAULT 0,
    playoff_win MEDIUMINT DEFAULT 0,
    playoff_loss MEDIUMINT DEFAULT 0,
    PRIMARY KEY(coachid)
);
CREATE TABLE coaches_season (
    coachid VARCHAR(9) NOT NULL,
    year SMALLINT,
    yr_order TINYINT,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    season_win MEDIUMINT DEFAULT 0,
    season_loss MEDIUMINT DEFAULT 0,
    playoff_win MEDIUMINT DEFAULT 0,
    playoff_lost MEDIUMINT DEFAULT 0,
    team CHAR(3) NOT NULL,
    PRIMARY KEY(coachid, year, yr_order, team),
    FOREIGN KEY(coachid, firstname, lastname) REFERENCES coaches_career(coachid, firstname, lastname),
    FOREIGN KEY(team) REFERENCES teams(team)
);